### PR TITLE
temporary local fix for gcc isnan error

### PR DESCRIPTION
**Pull request by lavrod**
Every time I take new grit-engine I need to do this fix to succeed to compile on Linux Ubuntu 16.04LTS
example of error:

```
engine/lua_wrappers_core.cpp: In function ‘int global_check_nan(lua_State*)’:
engine/lua_wrappers_core.cpp:726:41: error: ‘isnan’ was not declared in this scope
             if (isnan(lua_tonumber(L, i))) {
                                         ^
engine/lua_wrappers_core.cpp:726:41: note: suggested alternative:
In file included from dependencies/grit-ogre/OgreMain/include/OgreStdHeaders.h:28:0,
                 from dependencies/grit-ogre/OgreMain/include/OgrePrerequisites.h:367,
                 from dependencies/grit-ogre/OgreMain/include/Ogre.h:31,
                 from dependencies/stdafx/stdafx.h:1:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
```
```
 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
```

### CODE REVIEW

**Comment by lavrod** [comment]
Cannot compile on Window.

**Comment by sparkprime** [comment]
Does it work if you instead convert the isnan calls to std::isnan ?  Failing that there is a my_isnan in #include <math_util.h> so I don't think defining another one is a good idea.  But my_isnan isn't actually used anywhere in the code at all... So I would say if std::isnan works, then use that, and we'll delete my_isnan.

**Comment by lavrod** [comment]
Ok works under my linux by replacing with std:isnan.
Did a make clean and make -j 4

**Comment by sparkprime** [comment]
Ok can you do a git rebase -i master and squash the two commits together, then push -f
That means we can merge a tidy PR with only one change without the intermediate ifdef stuff.
